version: "3.8"

services:
  app:
    image: ksan319/blood_spot:latest
    container_name: "blood_spot_api"
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./src/main/resources/application.yaml:/app/application.yaml
    depends_on:
      - db
    restart: "always"
    develop:
      watch:
        - action: rebuild
          path: .

  db:
    image: postgres:15
    restart: "always"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  pgdata:
