spring:
  application:
    name: blood-spot-bot-api

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true


telegram:
  bot:
      name: BloodDonationsSpotterBot
      token: ${BOT_TOKEN}

donor-source:
  base-url: ${BASE_URL}
  valid-location: ${VALID_URL}

commands:
  menus:
    start:
      text: "👋 Привет! Я помогу вам следить за окошками для записи на донацию в Центр крови им. О.К. Гаврилова."
      buttons:
        - label: "Подписаться"
          callback: "/site"
    auth:
      text: "У Центра крови нет публичного расписания для записи. Оно доступно только в вашем личном кабинете. Чтобы я мог следить за появлением свободных окошек для записи, мне понадобятся ваш логин и пароль.\n\n👉 Введите через пробел ваш логин и пароль от личного кабинета на сайте %s.\nПример: my@email.com password"
      buttons:
        - label: "Написать в поддержку"
          callback: ${SUPPORT_CHAT_URL}
    main:
      text: "*%s*, отлично, всё получилось! Теперь я сам буду следить за новыми окошками для записи и сообщать вам о том, что они появились 😌\n\n_Ваша подписка:_ *%s*\n_Адрес центра:_ *%s*"
      buttons:
        - label: "Включить/отключить подписку"
          callback: "/subscribe"
        - label: "Сменить адрес центра для записи"
          callback: "/site"
        - label: "---"
          callback: "ROW"
        - label: "Написать в поддержку"
          callback: ${SUPPORT_CHAT_URL}
    authError:
      text: "🤔 Не получилось войти в личный кабинет. Проверьте логин и пароль, и попробуйте снова."
      buttons:
        - label: "Вернуться на назад"
          callback: "/start"
    chooseSite:
      text: "Выберите адрес центра крови, в который хотите записаться:"
      buttons:
        - label: "Поликарпова"
          callback: "/site_donor"
        - label: "Шаболовка"
          callback: "/site_sab"
        - label: "Царицыно"
          callback: "/site_zar"
        - label: "---"
          callback: "ROW"
        - label: "Написать в поддержку"
          callback: ${SUPPORT_CHAT_URL}
    newSpotsFound:
      text: "😺 *Появились окошки для записи!* \n %s"
      buttons:
        - label: "Записаться"
          callback: "%2$s"
