name: Docker Image CI
env:
  - CI/CD

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_TOKEN }}

      - name: Set image tag
        id: meta
        run: |
          echo "tag=ksan319-pet/blood_spot:${{ github.sha }}" >> $GITHUB_OUTPUT
          echo "latest=ksan319-pet/blood_spot:latest" >> $GITHUB_OUTPUT

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ steps.meta.outputs.tag }} --tag ${{ steps.meta.outputs.latest }}

      - name: Push the Docker image
        run: |
          docker push ${{ steps.meta.outputs.tag }}
          docker push ${{ steps.meta.outputs.latest }}
